### ISSUE TITLE
IP address of boot2docker-vm on host-only network is unpredictable

### ISSUE THREAD

**Issue by mdub** [boot2docker/boot2docker-cli#100]
My boot2docker-vm currently has IP address 192.168.59.107 on the host-only network, and I'm able to successfully talk to it from the (OS X) host.

However, if I recreate the VM, I'm likely to get a different IP address.  This makes it difficult to (for example) write test scripts, or configure a "local docker" alias in /etc/hosts.

**Comment by matschaffer** [comment]
I'll throw in word here that some way to configure virtualbox private networking for boot2docker would be a bonus.

My use case is that I have an app (grafana) using google's oauth.

If the IP changes I need to reconfigure the set of allowed redirects on google's side which is kind of a pain.

@dezmodue's trick of setting the dhcp low=high is a decent work around for now though. Especially when paired with the `boot2docker config` docs on https://github.com/boot2docker/boot2docker-cli

**Comment by mdub** [comment]
Actually, @matschaffer, I've since moved back to boot2docker-cli again. :-)

FWIW, the Vagrant setup I used to use is at https://github.com/mdub/localdocker

**Comment by matschaffer** [comment]
Sweet! I may stay on it as well since it's not too often that I need to
totally reset it and the removal of the vmnet is a decent workaround.

2015年5月7日木曜日、Mike Williams<notifications@github.com>さんは書きました:

> Actually, @matschaffer <https://github.com/matschaffer>, I've since moved
> back to boot2docker-cli again. :-)
>
> FWIW, the Vagrant setup I used to use is at
> https://github.com/mdub/localdocker
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boot2docker/boot2docker-cli/issues/100#issuecomment-99818088>
> .
>


-- 

-Mat

about.me/matschaffer

**Comment by matschaffer** [comment]
For anyone reading along, I found a caveat the "remove vmnet" work around. Seems that the network's DHCP doesn't reset if there are other vmnets still active (e.g., a set docker-machine vms).

So I had to clear both out of the way, remove all vmnets, then I got back to the typical 192.168.59.103
