### ISSUE TITLE
VM created by init does not have DNS set up correctly

### ISSUE THREAD

**Issue by devinsba** [boot2docker/boot2docker-cli#102]
I tried using the current master with the latest boot2docker ISO but the networking is not being initialized correctly. I tried to pull down a docker image but was told the host could not resolve. When I added `nameserver 8.8.8.8` to my `/etc/resolv.conf` I was able to connect.

**Comment by mcoms** [comment]
I encountered what looks like this issue, but is possibly another — my Macbook's DNS resolver is `127.0.0.1`. `boot2docker init` was copying this value for the VM's `/etc/resolv.conf`.

If I manually edit the VM's `resolv.conf` to be:
```
nameserver 192.168.59.99
```

Things start working. This IP is the same as `DHCPIP` from `profile`, and it provided by Virtualbox for guest DNS requests.

**Comment by blixt** [comment]
I encountered the same thing as @mcoms, where it used the IP of my router which broke the moment I switched networks:

```
docker@boot2docker:~$ cat /etc/resolv.conf
search home
nameserver 192.168.1.1
```

I changed it to Google's Public DNS `8.8.8.8` which fixed it. Is there any way to use a better default or at least warn the user that a local IP is being used?

**Comment by sra** [comment]
This issue happens for me when I'm running DNSCrypt from OpenDNS which proxies DNS requests encrypted. The nameserver is set on the mac when enabled to 

`nameserver 127.0.0.54`

But it isn't resolvable from inside the docker vm, obviously.

**Comment by ferrix** [comment]
Confirming with 4.3.20 and 1.5.0

**Comment by mull** [comment]
Confirming 

```
Boot2Docker-cli version: v1.7.1
Docker version 1.7.1, build 786b29d
```

The workaround `echo "nameserver 8.8.8.8" > /etc/resolv.conf && sudo /etc/init.d/docker restart` worked for me.

**Comment by mull** [comment]
^ adding to that: Worked before I shut down my computer & went home. Probably unrelated but adding in case it helps. :)

**Comment by ravwojdyla** [comment]
The same problem, in boot2docker and just upgraded to docker-machine - still a problem.

docker-machine version 0.4.1 (e2c88d6)
Docker version 1.8.1, build d12ea79
Boot2Docker version 1.8.1

Btw in my case I got only first of 3 search domains, after I manually add the rest, things got better.

**Comment by stevenolen** [comment]
same problem on mine:

`Boot2Docker-cli version: v1.5.0, Git commit: ccd9032`
`Docker version 1.8.1, build d12ea79`
`docker-machine version 0.4.1 (e2c88d6)`

**Comment by jpdesigndev** [comment]
Same problem here:

OS X 10.9.5
docker-machine version 0.4.1 (e2c88d6)

**Comment by carloscheddar** [comment]
When running ruby containers I kept running into this error:

    Gem::RemoteFetcher::UnknownHostError: no such name

The temporary fix worked for me but as others have said it reverts to the original DNS after the virtual machine restarts. So I ended up just running this one liner after the VM boots.

    $ docker-machine ssh MACHINE_NAME "echo 'nameserver 8.8.8.8' > /etc/resolv.conf && sudo /etc/init.d/docker restart"

`OS X 10.10.5`
`Docker version 1.8.1, build d12ea79`
`docker-machine version 0.4.1 (e2c88d6)`

**Comment by jjqq2013** [comment]
+1. When switch WiFi network, the boot2docker still remember old dns server which became invalid.
I have to docker-machine restart or change /etc/resolv.conf

**Comment by dionysiusmarquis** [comment]
It helped me to use the host's resolver:

`VBoxManage modifyvm "VM name" --natdnshostresolver1 on`

https://superuser.com/questions/641933/how-to-get-virtualbox-vms-to-use-hosts-dns/722670#722670

**Comment by mahnunchik** [comment]
Any news?

Command:
```
$ docker-machine create --engine-opt dns=1.2.3.4 --engine-opt dns=8.8.8.8 test
```

skips `engine-opt`.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
