### ISSUE TITLE
"boot2docker up" should init VM if it doesn't exist

### ISSUE THREAD

**Issue by bfirsh** [boot2docker/boot2docker-cli#103]
It would be nice if getting started were just one command.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
