### ISSUE TITLE
`boot2docker-cli --param value cmd` does not work

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#104]
it looks like the `=` is not optional in `pflag`. It would be good to move to the `mflag` used by Docker - for consistency.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
