### ISSUE TITLE
think about modifying an existing vm

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#109]
for example, assuming I already have a `test` vm, maybe I should be able to 

`b2d modify --vm test --iso other.iso` and then start it again

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
