### ISSUE TITLE
can a command failure then print the `-v` log even when it was not specified?

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#117]
so that users can send us debug info from when the problem happened

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
