### ISSUE TITLE
remove the need to manually set the DOCKER_HOST

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#131]
irc discussions with @shykes indicate that making `boot2docker up` add a `dockerhost` setting to the ~/.dockercfg file is the most sane.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
