### ISSUE TITLE
it seems that vboxmanage start can fail and we don't detect it

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#139]
vboxmanage is not returning an error - unless we hand parse its output :(

eg, create with an invalid serial pipe path on windows.

longer term we need to look at parsing the output, for now, call vbox status in cmdUp

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
