### ISSUE TITLE
add helpers to prompt users to upgrade their manage tool

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#149]
now that we're linking versions, its much more important for them to update the `boot2docker` tool too.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
