### ISSUE TITLE
Port forwarding doesn't work properly 1.0.0

### ISSUE THREAD

**Issue by gliush** [boot2docker/boot2docker-cli#152]
I'm following [this manual](http://docs.docker.com/userguide/usingdocker/) with slight changes
- Install [1.0.0 version of docker](https://github.com/boot2docker/osx-installer/releases/tag/v1.0.0)
- Remove all previous files

```
$ rm .boot2docker/boot2docker.iso
$ boot2docker delete
```
- Create new vm image

```
$ boot2docker init
2014/06/12 15:39:17 Creating VM boot2docker-vm...
2014/06/12 15:39:17 Apply interim patch to VM boot2docker-vm (https://www.virtualbox.org/ticket/12748)
2014/06/12 15:39:18 Setting NIC #1 to use NAT network...
2014/06/12 15:39:18 Port forwarding [ssh] tcp://127.0.0.1:2022 --> :22
2014/06/12 15:39:18 Port forwarding [docker] tcp://127.0.0.1:2375 --> :2375
2014/06/12 15:39:18 Setting NIC #2 to use host-only network "vboxnet0"...
2014/06/12 15:39:18 Setting VM storage...
2014/06/12 15:39:27 Done. Type `boot2docker up` to start the VM.
```
- Run it

```
$ boot2docker up
2014/06/12 14:50:39 Waiting for VM to be started...
...........
2014/06/12 14:51:01 Started.
2014/06/12 14:51:01 Auto detection of the VM's IP address.
```
- Run docker image

```
$ docker run -d -P training/webapp python app.py
```
- Find the port 

```
$ docker port c6073a9fc281 5000
0.0.0.0:49153
```
- Check if it works

```
curl localhost:49153
... hangs!!! 
```
- Check that in VirtualBox it works

```
$ boot2docker ssh "curl localhost:49153" 2>/dev/null
Hello world!
```
- And by the way, manual port forwarding doesn't help either!

```
$ i=49153;
$ VBoxManage modifyvm "boot2docker-vm" --natpf1 "tcp-port$i,tcp,,$i,,$i";
$ VBoxManage modifyvm "boot2docker-vm" --natpf1 "udp-port$i,udp,,$i,,$i";
```

What should I do to make it work?

**Comment by velvia** [comment]
BTW, I still cannot get the latest boot2docker(-cli) (v1.6.0) to get ports forwarded correctly.   When I launch the service on the docker VM (via boot2docker ssh), then I can do a curl locally:

```
docker@boot2docker:~$ curl localhost:3000/
<a href="/login">Found</a>.
```

but if I do a curl from my OSX host, using the boot2docker ip, then it just hangs.

```
docker@boot2docker:~$ docker ps
CONTAINER ID        IMAGE                    COMMAND                CREATED             STATUS              PORTS                    NAMES
47a3eacaae97        grafana/grafana:latest   "/usr/sbin/grafana-s   5 minutes ago       Up 5 minutes        0.0.0.0:3000->3000/tcp   nostalgic_rosalind
```

**Comment by orangeudav** [comment]
+1 
I am using latest boot2docker-cli 1.6.2. But "docker run -p xxx ..." not forward ports to my host (mac os).
Is it work of boot2docker-cli of monitoring docker vm and correctly setting up "VBoxManage controlvm "boot2docker-vm" natpf1 blablabla" in background?

**Comment by ssmith15** [comment]
+1

**Comment by fgarcia** [comment]
I am also having problems, but in my case it is just that the `-P` parameter does not work, instead I must use `-p`

I've just reproduced this with the 'nginx' image

    docker run -d -P --name web nginx
    docker run -d -p 80:80 --name web nginx

The first line fails, the second on works. The only difference is that the second line forces the random port to match the forwarded port.

**Comment by jodem** [comment]
@fgarcia  made my day I spent 1h30  on it and it finally works. I ran port mapping through docker file and it seems we have to set it manually when we start the image. Thanks !
