### ISSUE TITLE
"boot2docker init" fails without useful error if vm settings file already exists

### ISSUE THREAD

**Issue by yozlet** [boot2docker/boot2docker-cli#155]
```
Angelou:~ yoz$ /usr/local/bin/boot2docker init 
2014/06/09 17:39:40 Creating VM boot2docker-vm...
2014/06/09 17:39:40 FIRST: Failed to create VM "boot2docker-vm": exit status 1
2014/06/09 17:39:40 Failed to create VM "boot2docker-vm": exit status 1
```

This stumped me for a while until I realised that there's a `-v` option, which then revealed:

```
2014/06/16 16:32:22 executing: VBoxManage createvm --name boot2docker-vm --register
VBoxManage: error: Machine settings file '/Users/yoz/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox' already exists
```

(I assume that the settings file was already there because I'd initially used boot2docker through homebrew, then uninstalled it and used the boot2docker Mac installer app.)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
