### ISSUE TITLE
boot2docker download <url>

### ISSUE THREAD

**Issue by mattes** [boot2docker/boot2docker-cli#171]
Will updates here (https://github.com/boot2docker/boot2docker-cli/blob/master/cmds.go#L544) to allow .iso downloads from custom URLs be merged?

see https://github.com/boot2docker/boot2docker/pull/284 for background, why i am posting this.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
