### ISSUE TITLE
Uninstall instructions on OS X

### ISSUE THREAD

**Issue by matthughes** [boot2docker/boot2docker-cli#172]
I installed boot2docker CLI by the package.  How do you uninstall?  I know I can delete the VM and ISO, but I want the 'docker' command completely gone.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
