### ISSUE TITLE
windows service 

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#201]
http://sanatgersappa.blogspot.com.au/2013/07/windows-service-with-go-easy-way.html

hint for later :)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
