### ISSUE TITLE
Automatically mount home directory

### ISSUE THREAD

**Issue by bfirsh** [boot2docker/boot2docker-cli#202]
(This is a reopening of https://github.com/boot2docker/boot2docker/issues/84 now that the CLI is a separate project.)

This is related to https://github.com/boot2docker/boot2docker/pull/284. If the boot2docker VM has some way of mounting directories on the host machine, it is pretty useless unless this is exposed somehow in the CLI.

The simplest and most powerful option I can see is automatically mounting your home directory at the same place inside the VM. For example, mounting `/Users/ben` on OS X at `/Users/ben` inside the VM. This works brilliantly for Docker volumes, because you can run `docker run -v .:/code ...` and it Just Works because `.` expands to `/Users/ben/...`.

It could also mount the entirety of `/Users`, but I'm not sure on the details of how the permissions would work.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
