### ISSUE TITLE
[FTUX] Boot2Docker needs to update the docker client binary (and maybe itself too)

### ISSUE THREAD

**Issue by j0hnst0n** [boot2docker/boot2docker-cli#212]
@SvenDowideit 
A first-time user experience (FTUX).  They type-in the "ambitious ubuntu" line suggested by the "hello-world" image and get the following "flag provided but not defined":

Is this the expected behavior? 

![image](https://cloud.githubusercontent.com/assets/1610391/3814989/48f3b0e6-1cc0-11e4-9c02-eca643d83952.png)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
