### ISSUE TITLE
Allow bridged or NAT networking as an optional alternative to host-only network

### ISSUE THREAD

**Issue by jonbca** [boot2docker/boot2docker-cli#213]
The host-only network that boot2docker exposes (via vbox) is not compatible with the Cisco Anyconnect VPN client. The VPN client (when running in split-tunnel mode) automatically adds firewall rules (at least on MacOS it does). The firewall rules block all network traffic except the whitelisted hosts on the VPN network, and the public internet over the en\* ports. In effect, all network traffic via vboxnet0 is firewalled off.

If boot2docker made bridged or NAT networking available as an alternative to host-only networking, then Cisco AnyConnect VPN users could access their boot2docker hosts.

I realise that this opens a potential security hole, however I believe the impact is low because it would typically only be used by Cisco VPN users. The alternative is having no docker, which I think is worse.

**Comment by wizonesolutions** [comment]
@knownasilya Did you ever find out how the firewall actually works? No matter what I try, `pfctl` looks pretty empty. Even `sudo pfctl -a com.apple/250.ApplicationFirewall -sr`...

**Comment by wizonesolutions** [comment]
I had to update AnyConnect. Then I was able to use the network as long as it was created while not on the VPN. So for me that was:

`vagrant up --no-provision`

* connect to vpn *

`vagrant provision`

but for boot2docker that last step may be superfluous

**Comment by dchenbecker** [comment]
Just to throw this out there: OpenConnect has been updated to work with Mavericks and Yosemite and works flawlessly with our ASAs for access. Bonus: it doesn't mess with pfctl so boot2docker works just fine without any futzing around.

**Comment by bortels** [comment]
Fwiw - openconnect was where I finally landed. Unfortunately, in many
corporate environments, that lands you kinda out-of-bounds. I personally
*prefer* being out-of-bounds, but I suspect that's very much not the norm.
Finding a reasonable solution for Cisco anyconnect other than "replace it"
is probably desirable, if no longer absolutely necessary.

**Comment by FrancoisZhang** [comment]
Does anybody know how to fix it with Yosemite + Cisco Anyconnect? I stuck in here. Too many discussion I found but haven't found any suggestion works. The "ipfw" is removed from Yosemite now. Thanks a lot.

**Comment by knownasilya** [comment]
@FrancoisZhang try https://github.com/boot2docker/boot2docker/issues/628#issuecomment-68909772

**Comment by wizonesolutions** [comment]
Use openconnect if you can.

brew cask install tuntap # needs homebrew cask
brew install openconnect

**Comment by keenaudio** [comment]
Setting up port forwarding in Virtual Box worked for me, as described here: https://github.com/boot2docker/boot2docker/issues/628#issuecomment-68909772 (thanks @johnnyt)
I used the Virtual Box UI (Settings / Network) Network type should be NAT. Click on port forwarding and add a rule to forward on 127.0.0.1:2376, then update your ~/.profile file: 

export DOCKER_HOST=tcp://127.0.0.1:2376

**Comment by norbertpy** [comment]
openconnect is awesome:
```bash
$ brew install openconnect
$ sudo openconnect --user={username} {vpn-hostname}
```

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
