### ISSUE TITLE
Configurable for the virtualbox path

### ISSUE THREAD

**Issue by magixyu** [boot2docker/boot2docker-cli#216]
Currently it is hardcoded to drive C.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
