### ISSUE TITLE
boot2docker init does not work behind proxy on Windows

### ISSUE THREAD

**Issue by da9l** [boot2docker/boot2docker-cli#230]
I'm sitting behind a corporate proxy and I suspect that it is the reason this happens when I run boot2docker.exe init:

``` powershell
C:\Program Files\Boot2Docker for Windows> boot2docker init
2014/08/22 10:46:42 Downloading boot2docker ISO image...
2014/08/22 10:46:43 Failed to get latest release: Get https://api.github.com/repos/boot2docker/boot2docker/releases: dial tcp 192.30.252.137:443: ConnectEx tcp: No connection could be made because the target machine actively refused it.
```

Is there a way to configure proxy settings for boot2docker.exe ?

**Comment by Sunnykaby** [comment]
@siriwatj  YES, this method solved my problem. That's  wonderful~

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
