### ISSUE TITLE
`boot2docker init` does not download the iso if it doesn't have one

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#232]
this was lost in the multi-hypervisor refactor.

some refactoring of the `cmd.go` is needed as `boot2docker --init up` does not work - it doesn't make ssh keys, and doesn't download either - it should (optionally) call cmdInit, and B2D.GetMachine should probably have its 'init' code separated back out.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
