### ISSUE TITLE
`boot2docker init` does not check to see if vbox is installed

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#234]
need to add a `isItThere()` to the driver interface

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
