### ISSUE TITLE
False udp "port is already allocated" when restarting containers?

### ISSUE THREAD

**Issue by jamshid** [boot2docker/boot2docker-cli#250]
Anyone else seeing this error occasionally with boot2docker 1.2 (OSX, brew installed)? It might be specified to udp, I've also seen this with my dnsmasq container which runs with "-p 53:53/udp".

I started the container with "-p 161:161/udp" later try to restart it.

```
$ docker restart foo1
Error response from daemon: Cannot restart container foo1: Bind for 0.0.0.0:161 failed: port is already allocated
2014/09/04 12:13:12 Error: failed to restart one or more containers
```

Should docker-proxy still be running? The container is stopped (verified with "docker ps -a" and "docker stop foo1"). 

```
$ bootdocker ssh sudo ps | grep 161
18425 root     docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 161 -container-ip 172.17.1.112 -container-port 161
```

Killing docker-proxy doesn't fix the problem though. Need to "boot2docker restart".

Is iptables causing the port conflict? `sudo iptables --list` shows some mappings like
`ACCEPT     udp  --  anywhere             172.17.0.2           udp dpt:domain`

I sometimes restart the docker service to pick up DNS changes, do I need to do something else to reinitialize networking or should  "/usr/local/etc/init.d/docker restart" take care of it all?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
