### ISSUE TITLE
boot2docker init --vm=second-vm doen't detect that it needs a different sshport

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#253]
I _think_ this used to work. Now, if you

```
boot2docker init
boot2docker start
boot2docker  --vm=testme init
boot2docker  --vm=testme start
```

the second `start` will report the wrong IP address - the `init` should fail due to attempting to reuse the nat port forwarded sshport that is used for bootstrapping.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
