### ISSUE TITLE
Forward /var/run/docker.sock

### ISSUE THREAD

**Issue by zimbatm** [boot2docker/boot2docker-cli#257]
It would be nice if boot2docker would forward traffic from `/var/run/docker.sock` instead of having to fiddle with environment variables.

This means that some sort of daemon needs to run for the lifetime of the VM. Right now I'm just using that simple little script: https://gist.github.com/zimbatm/6b815e947619fe47a41a

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
