### ISSUE TITLE
64-bit Tiny Core Linux (feature request)

### ISSUE THREAD

**Issue by sjackman** [boot2docker/boot2docker-cli#264]
boot2docker currently uses Tiny Core Linux, which provides a 64-bit kernel and a 32-bit user-space. Please provide an option to use [Tiny Core Pure 64](http://distro.ibiblio.org/tinycorelinux/5.x/x86_64/release/) which provides a 64-bit kernel and a 64-bit user-space. Thanks!

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
