### ISSUE TITLE
Multiple boot2docker vms all try to use the same port for ssh forwarding

### ISSUE THREAD

**Issue by hugoduncan** [boot2docker/boot2docker-cli#278]
When using multiple boot2docker vms (created with the `--vm` flag), all vms use the same port for ssh forwarding.  This results ins the boot2docker `ssh`, `socket`, etc commands reporting information for the wrong vm.

```
$ vboxmanage showvminfo boot2docker-vm --machinereadable | grep Forwarding
Forwarding(0)="ssh,tcp,127.0.0.1,2022,,22"
$ vboxmanage showvminfo boot2docker-vm2 --machinereadable | grep Forwarding
Forwarding(0)="ssh,tcp,127.0.0.1,2022,,22"
```

While a ssh port can be specified at init time with `--sshport`, it took a while to realise this was needed.  Some sort of warning mentioning `--sshport` when specifying a non-default vm name might be sufficient to help others avoid debugging this.

**Comment by RomanSaveljev** [comment]
This is an issue for me as well

**Comment by marclennox** [comment]
+1

**Comment by marclennox** [comment]
On this subject, I've used the --sshport option and it seems that it only has impact on the initial "boot2docker init".  After that, even if you specify a different port with "boot2docker start" it uses the original port, unless you manually change the Virtualbox port forward.

I even tried changing the ssh port in the profile config to something different, seems to have no impact.  How does "boot2docker ssh" know which port to use?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
