### ISSUE TITLE
boot2docker upgrade should warn if the cli is outdated

### ISSUE THREAD

**Issue by proppy** [boot2docker/boot2docker-cli#294]
It would be nice if boot2docker upgrade warned you that a new version of the cli is available and that you should update your binary.

For the 1.2->1.3 transition, if you do:

```
boot2docker upgrade
$(boot2docker shellinit)
# Writing /home/proppy/.docker/boot2docker-vm/ca.pem:
# Writing /home/proppy/.docker/boot2docker-vm/cert.pem:
# Writing /home/proppy/.docker/boot2docker-vm/key.pem:
#    export DOCKER_HOST=tcp://192.168.59.103:2376
#    export DOCKER_CERT_PATH=/home/proppy/.docker/boot2docker-vm
docker version
```

It will fails with:

```
$ docker version
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f
OS/Arch (client): linux/amd64
2014/10/16 18:33:03 Get http://192.168.59.103:2376/v1.15/version: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

Because `DOCKER_TLS_VERIFY` is not set

**Comment by tianon** [comment]
@proppy can you confirm that #242 fixed this issue for you?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
