### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by unbalancedparentheses** [boot2docker/boot2docker-cli#297]
I am a http://fishshell.com/ user. The shell is awesome but it is on purpose not 100% POSIX compliant. I would be glad to add code to https://github.com/boot2docker/boot2docker-cli/blob/master/cmds.go#L194-L204 so that it prints how to export the variables in fish.

The equivalent of

``` bash
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/unbalancedparentheses/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1
```

In fish would be

``` bash
set -x DOCKER_HOST=tcp://192.168.59.103:2376
set -x DOCKER_CERT_PATH=/Users/unbalancedparentheses/.boot2docker/certs/boot2docker-vm
set -x DOCKER_TLS_VERIFY=1
```

I could also detect if the user is using fish with basename $SHELL and print the correct way to export the variables.

Let me know what you think so that I code it.

Thanks in advance!

**Comment by bucaran** [comment]
Just adding myself here.

**Comment by bucaran** [comment]
Just adding myself here.

**Comment by rstacruz** [comment]
time to close this now.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
