### ISSUE TITLE
`boot2docker shellinit` on Windows prints commands that can not be used in cmd.exe or in a cygwin terminal

### ISSUE THREAD

**Issue by gmlewis** [boot2docker/boot2docker-cli#301]
Did the output from `boot2docker shellinit` change recently on Windows?

We used to not require cygwin, correct?  With v1.3.0, I get:

``` cmd
> boot2docker shellinit
Writing C:\Users\gmlewis\.boot2docker\certs\boot2docker-vm\ca.pem
Writing C:\Users\gmlewis\.boot2docker\certs\boot2docker-vm\cert.pem
Writing C:\Users\gmlewis\.boot2docker\certs\boot2docker-vm\key.pem
    export DOCKER_CERT_PATH=C:\Users\gmlewis\.boot2docker\certs\boot2docker-vm
    export DOCKER_TLS_VERIFY=1
    export DOCKER_HOST=tcp://192.168.59.105:2376
```

`export` only works in a cygwin terminal... and if I run the commands, I get:

``` cmd
$ echo $DOCKER_CERT_PATH
C:Usersgmlewis.boot2dockercertsboot2docker-vm
```

So I'm guessing we first need to go back to using `set` or if we require cygwin, then we put the path in single quotes to that `bash` doesn't try to parse it.  I don't remember now if v1.2.0 typed `set` or `export`, but now that there are 3 variables, it is probably more important for us to standardize on either `cmd.exe` or a cygwin terminal on Windows.

**Comment by edmorley** [comment]
This can be closed - it was fixed as part of https://github.com/boot2docker/boot2docker-cli/pull/356 - where single quotes were added around the value assigned to DOCKER_CERT_PATH.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
