### ISSUE TITLE
add command to switch between version

### ISSUE THREAD

**Issue by proppy** [boot2docker/boot2docker-cli#306]
It'd be cool to have a new command to download and switch between version of the iso.

example:

```
$ b2d use 1.3.1
downloading 1.3.1 ...
using 1.3.1
$ b2d use 1.3.0
using 1.3.0
$ b2d version
iso: 1.3.0
```

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
