### ISSUE TITLE
boo2docker should provide a way to set daemon flags

### ISSUE THREAD

**Issue by proppy** [boot2docker/boot2docker-cli#309]
Either throught flag or configuration, it'd be nice to have a way to mess with the daemon flags without ssh'ing into the VM and restarting the daemon.

That'd esp. be handy with the new --insecure-registry flag to allow running registry on localhost.

Related:
https://github.com/docker/docker/issues/8887
https://github.com/docker/docker/issues/8889
https://github.com/docker/docker/pull/8898

**Comment by SQiShER** [comment]
+1 - it would be nice if the `EXTRA_ARGS` would somehow survive boot2docker upgrades.

**Comment by daniel-bryant-uk** [comment]
+1 to @CleanCut's solution. Many thanks!

**Comment by CleanCut** [comment]
@daniel-bryant-uk Glad it could help someone!  I'm still mystified as to why boot2docker and docker seem to be content to leave this in such a user-unfriendly state!

**Comment by Moghedrin** [comment]
@CleanCut Because boot2docker-cli is officially pending deprecation as of https://github.com/boot2docker/boot2docker-cli/pull/334.

**Comment by CleanCut** [comment]
@Moghedrin Whaaaat???  boot2docker itself is going away?  This is news to me!

To summarize for the others in this thread who also don't know, boot2docker is being mothballed.  Everyone is being redirected to use the (apparently new) official docker "machine" project [here](https://github.com/docker/machine).

Man, every time I think I get something figured out with respect to docker, it changes out from under me.

**Comment by daniel-bryant-uk** [comment]
Wow - yeah, I have been keenly following Docker machine, but didn't realise that it would deprecate boot2docker...

I suppose this does make sense, but I don't think this is being communicated enough to the community

**Comment by Moghedrin** [comment]
@CleanCut It is going away, but nobody should be being redirected yet, as Docker Machine is still in its early stages. While boot2docker-cli is *pending* deprecation, it's still the official solution to use.

**Comment by CleanCut** [comment]
@Moghedrin Thanks for the clarification.  It appears they've only ever had two official alpha releases so far.  It looks like an ambitious project, though.  Are boot2docker devs moving over there to help out as well?

**Comment by Moghedrin** [comment]
@CleanCut If the maintainers want to contribute there, then nothing is stopping them - open source ftw! Outside of that, I don't know, and it seems rather early to be making guesses.

**Comment by sscarduzio** [comment]
+1

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
