### ISSUE TITLE
Custom "--vbox-share" directories are not auto-mounted

### ISSUE THREAD

**Issue by edmorley** [boot2docker/boot2docker-cli#314]
https://github.com/boot2docker/boot2docker-cli/pull/258 added support for a new "--vbox-share" parameter.

boot2docker help says:

```
  --vbox-share=[]: (defaults to 'C:\Users=c/Users' if no shares are specified; use 'disable' to explicitly prevent any shares from being created) List of directories to share during 'up|start|boot' via VirtualBox Guest Additions, with optional labels
```

Trying this:

$ boot2docker start -v --vbox-share="C:\foo"
Boot2Docker-cli version: v1.3.1
Git commit: 57ccdb8
2014/11/23 15:15:09 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2014/11/23 15:15:10 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountPrefix /
2014/11/23 15:15:10 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountDir /
2014/11/23 15:15:10 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe sharedfolder add boot2docker-vm --name C:\foo --hostpath C:\foo --automount
2014/11/23 15:15:10 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe setextradata boot2docker-vm VBoxInternal2/SharedFoldersEnableSymlinksCreate/C:\foo 1
2014/11/23 15:15:10 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm boot2docker-vm --type headless Waiting for VM "boot2docker-vm" to power on...
VM "boot2docker-vm" has been successfully started.
2014/11/23 15:15:11 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
Waiting for VM and Docker daemon to start...
...
$ boot2docker.exe ssh
...
Boot2Docker version 1.3.1, build master : 9a31a68 - Fri Oct 31 03:14:34 UTC 2014
Docker version 1.3.1, build 4e9bbfa
docker@boot2docker:~$ ls /c/
Users/

**Comment by johnw** [comment]
Another workaround:  Per this documentation https://github.com/boot2docker/boot2docker under "VirtualBox Guest Additions:" 
````
The first of the following share names that exists (if any) will be automatically mounted at the location specified:

    Users share at /Users
    /Users share at /Users
    c/Users share at /c/Users
    /c/Users share at /c/Users
    c:/Users share at /c/Users
```
(So boot2docker --vbox-share="c:\mymagicdata=/c/users" will auto mount.)   Not very flexible or useful long term, but it works.)

**Comment by edmorley** [comment]
See also boot2docker/boot2docker#678

**Comment by edmorley** [comment]
Closing this out to de-clutter my GitHub open issues dashboard since I believe this repo is deprecated.
