### ISSUE TITLE
boot2docker fails if the vbox vm has saved state?

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#318]
https://github.com/docker/docker/issues/7048#issuecomment-57627235

**Comment by md5** [comment]
I let my laptop get low on battery last night before putting it to sleep and managed to reproduce the latter scenario. Here's what I saw:

```
VBoxManage showvminfo boot2docker-vm --machinereadable | grep -i vmstate
VMState="saving"
VMStateChangeTime="2015-01-02T17:10:45.667000000"
```

It looks like that time is that time that I opened my laptop (in UTC).

**Comment by amegianeg** [comment]
I reproduced it with the same scenario: laptop got low on battery. I could see with Virtualbox "Saved" state of the instance. I ran:
```
amegia$ boot2docker up -v  
Boot2Docker-cli version: v1.3.1
Git commit: 57ccdb8
2015/05/06 00:59:32 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
error in run: Failed to get machine "boot2docker-vm": exit status 1
```
and
```
amegia$ VBoxManage showvminfo boot2docker-vm --machinereadable | grep -i vmstate
VBoxManage: error: The saved state file '/.../boot2docker-vm/Snapshots/2015-03-04T20-09-03-681588000Z.sav' is invalid (VERR_SSM_INTEGRITY_FOOTER). Delete the saved state and try again
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Console, interface IConsole, callee nsISupports
VBoxManage: error: Context: "COMGETTER(SharedFolders)(ComSafeArrayAsOutParam(folders))" at line 2186 of file VBoxManageInfo.cpp
VMState="saved"
VMStateChangeTime="2015-03-04T20:09:41.000000000"
VMStateFile="/.../boot2docker-vm/Snapshots/2015-03-04T20-09-03-681588000Z.sav"
```
I deleted the saved state, but nothing was fixed. Every b2d command I executed got:
`error in run: Failed to get machine "boot2docker-vm": exit status 1`

So I removed the machine in Virtualbox and `boot2docker init` againg and solved. Hope it helps

**Comment by vielmetti** [comment]
I seem to have run into a similar issue using `docker-compose` instead of `boot2docker`, complete with the same "exit status 1" message, and under similar circumstances of running out of battery. Removing the saved state in the VirtualBox Manager unwedged the system.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
