### ISSUE TITLE
Boot boot2docker.iso directly from Virtualbox?

### ISSUE THREAD

**Issue by ideallorn** [boot2docker/boot2docker-cli#323]
Hello,

I create a VM from virtualbox manually(allocated 20G space for the vmdk), and attach the offically boot2docker.iso and then start the vm, everything looks fine, but when I typed "df -h" I got

root@boot2docker:~# df -h
Filesystem        Size        Used    Available    Use% Mounted on
rootfs             445.6M  218.4M      227.2M       49% /
tmpfs              445.6M  218.4M      227.2M       49% /
tmpfs              247.5M            0      247.5M         0% /dev/shm

I'm wondering where is my 20G vmdk? and how can I mount it.  Many thanks.

dan

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
