### ISSUE TITLE
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file

### ISSUE THREAD

**Issue by nickchisiu** [boot2docker/boot2docker-cli#326]
I'm using boot2docker on OSX Yosemite with a CentOS 7 container `docker run -i --rm -t centos:centos7 /bin/bash` and when I'm trying to install httpd package `yum install httpd` I'm getting this error: 

`error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file`

**Comment by edmorley** [comment]
See also https://github.com/docker/docker/issues/6980

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
