### ISSUE TITLE
PlayFramework 2 doesn't get file updates

### ISSUE THREAD

**Issue by nickchisiu** [boot2docker/boot2docker-cli#327]
When I'm running Play Framework with command `play run` on a centos7 container the Play Framework doesn't get the file changes and re-compiling the code as it should be, I think is related to shared network folders or something

**Comment by tbatchelli** [comment]
Your suspicion is right. PlayFramework uses inotify to find out about changes in the filesystem. inotify does not work on remote file systems, and VBox shared folders are essentially remote file systems.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
