### ISSUE TITLE
How to set a fixed IP

### ISSUE THREAD

**Issue by icambron** [boot2docker/boot2docker-cli#330]
For various reasons, it's important for me to lock down the IP I use for boot2docker. It seems like there should be several ways to do that, but I can't seem to make any of them work:

Locking down the DCHP addresses:
```
LowerIP = "192.168.59.105"
UpperIP = "192.168.59.105"
```

```
-> boot2docker stop && boot2docker delete && boot2docker init && boot2docker start
Waiting for VM and Docker daemon to start...
..........................................................................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
Started.
  Trying to get Docker socket one more time
Error requesting socket: No IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:81:fb:ca brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe81:fbca/64 scope link
       valid_lft forever preferred_lft forever
```

Turning off DCHP, expecting it to use 192.168.59.3:
```
DHCPEnabled = false
```

But seems to use DCHP anyway? From output of `boot2docker start`:

```
    export DOCKER_HOST=tcp://192.168.59.103:2376
````

The kitchen sink of settings I almost, but not quite, understand:

```
DockerPort = 0
HostIP = "192.168.59.105"
NetMask = [255, 255, 255, 0]
DHCPEnabled = false
LowerIP = "192.168.59.105"
UpperIP = "192.168.59.105"
```

Starts OK, but `docker ps` hangs:

```
-> $(boot2docker shellinit 2>/dev/null) && docker ps
FATA[0032] An error occurred trying to connect: Get https://192.168.59.105:2376/v1.16/containers/json: dial tcp 192.168.59.105:2376: i/o timeout
```

What should I do?

**Comment by arturgspb** [comment]
+1

**Comment by icambron** [comment]
I understand now why what I did doesn't make sense: the DHCP range needs to contain all the addresses assigned to the Docker containers themselves. Still, you'd think it would be possible to set a static IP for the VM and have DHCP for the containers.

**Comment by arturgspb** [comment]
HI! I found answer to your question in Manual =)
Section "configuration" on page https://github.com/boot2docker/boot2docker-cli
