### ISSUE TITLE
--vm parameter is ignored by boot2docker init (UART pipe name)

### ISSUE THREAD

**Issue by RomanSaveljev** [boot2docker/boot2docker-cli#337]
The issue exists in Windows:

Steps to reproduce:
1. boot2docker --vm=test init
2. Open VirtualBox GUI and check out "Serial Ports" under **test** VM settings

Expected result:
- **Port/File Path** field says `\\.\pipe\test`

Actual result:
- **Port/File Path** field says `\\.\pipe\boot2docker-vm`

As the result, second VM fails to start

**Comment by RomanSaveljev** [comment]
This feature is not configurable for Windows CLI (unlike Linux). Looks like I will have to use VBoxManage directly..

**Comment by RomanSaveljev** [comment]
The same problem exists also when 2 VMs with default name (boot2docker-vm) are started under different Windows user accounts

**Comment by strogonoff** [comment]
(Apparently the problem with 2 VMs under different accounts (even if one of them is powered off) exists on OS X [Yosemite] as well.)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
