### ISSUE TITLE
boot2docker ssh docker run --volume failed

### ISSUE THREAD

**Issue by larrycai** [boot2docker/boot2docker-cli#338]
boot2docker 1.4.1/Windows 7.

I want to start the docker container in host (Windows) cmd shell

```
boo2docker ssh docker run -d --volume=/home/docker:/java larrycai/jenkins-slave-ubuntu
```

Unfortunately it reports

```
sh: syntax error: unexpected "("
error in run: exit status 2
```

WIthout `--volume=/home/docker:/java` it works fine, did I need to escape something to be passed into docker env ?

I noticed it append some environment to the path by using `docker ssh -vvv ...`

```
 debug1: Sending command: docker run -d --volume=C:\\Program Files (x86)\\Git\\home\\docker;C:\\Program Files (x86)\\Git\\java larrycai/jenkins-slave
```

Looks it is a bug ?

**Comment by larrycai** [comment]
I noticed it pass the host home directory to docker env by using `ssh -vvv`

debug1: Sending command: docker run -d --volume=C:\\Program Files (x86)\\Git\\home\\docker;C:\\Program Files (x86)\\Git\\java larrycai/jenkins-slave

Interesting to see it use boot2docker's host environment (Windows) instead of docker host environment (VM system).

Any possible to solve this ?

**Comment by childnode** [comment]
Try ```boo2docker ssh "docker run -d --volume=/home/docker:/java larrycai/jenkins-slave-ubuntu"```
^ use "" to encapsulate the command that you are willing to run in ssh

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
