### ISSUE TITLE
the cli needs to deal better with vbox not running

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#34]
at the moment, if vbox isn't started, it takes a long time for it to timeout - we should work out a way to detect it, and if possible launch it.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
