### ISSUE TITLE
boot2docker-cli closes with no warning - win 7 64-bit

### ISSUE THREAD

**Issue by Ajar-Ajar** [boot2docker/boot2docker-cli#346]
Hi all, the boot2docker-cli keeps closing with no warning.
absolutely annoying to have to start the client every 5 minutes...
any idea on how to fix this?
I tried un-installing and re-installing a dozen times already - still closes.
I'm running on win 7 64-bit, the docker vm on virtualbox runs fine,
It's only the cli client that require starting again every 5 minutes...
and it takes a long time to boot... although as I mentioned - the vm is constantly running in the background... not sure this is the intended behavior...
anyone?
Cheers

**Comment by AngellusMortis** [comment]
I am also having this issue. It looks like the SSH connection to the VM is being interrupted. Everytime I get disconnected, it gives me `Connection to 127.0.0.1 closed by remote host.`

**Comment by Si-Stone** [comment]
+1
...I get this same problem if I do the following on win7 64bit:
   boot2docker ssh

Workaround: do a direct ssh from a _cygwin_ terminal, i.e.:
   boot2docker shellinit
   [paste exports returned from the above]
   ssh docker@boot2docker
   [pw=tcuser]

That might help you as a workaround (as I'm guessing the --ssh option to boot2docker command might though I have not tried it).

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
