### ISSUE TITLE
make natdnshostresolver1 and natdnsproxy1 easily configurable via environment variables

### ISSUE THREAD

**Issue by lexinator** [boot2docker/boot2docker-cli#348]
would it be possible to expose natdnshostresolver1 and natdnsproxy1 through environment variables?

we have a large user base and having all of them run the required virtualbox commands to enable these options is unwieldy.

it'd be nice to tell our users to set environment variables so boot2docker will work out of the box for users on vpn.

thanks

References:
https://github.com/boot2docker/boot2docker-cli/pull/316
https://github.com/boot2docker/boot2docker-cli/pull/320

**Comment by packetcollision** [comment]
:+1:  In our testing, in "NAT DNS Proxy" mode the DNS performance is good enough, and not having to explain why people's containers are broken whenever they switch networks would be a huge benefit.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
