### ISSUE TITLE
ssh command should return exit code of the command that was ran

### ISSUE THREAD

**Issue by cjellick** [boot2docker/boot2docker-cli#352]
If you run something like:
`boot2docker ssh -t somescript.sh`
and that script exits with a non-zero exits code, boot2docker will always return exit code 1. It should return the exit code that the command returned.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
