### ISSUE TITLE
VM stops but message says it failed on Windows

### ISSUE THREAD

**Issue by jbarbier** [boot2docker/boot2docker-cli#357]
```
C:\Users\julien>boot2docker stop
error in run: Failed to stop machine "boot2docker-vm": exit status 1
```

```
C:\Users\julien>boot2docker version
Boot2Docker-cli version: v1.5.0
Git commit: ccd9032
```

**Comment by jbarbier** [comment]
PS: on windows 7

**Comment by ahmetalpbalkan** [comment]
@jbarbier can you please run with -v switch: `boot2docker stop -v`

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
