### ISSUE TITLE
boot2docker cli missing disk space usage, load, mem usage etc

### ISSUE THREAD

**Issue by cruatta** [boot2docker/boot2docker-cli#360]
Just ran into an issue where I ran out of free disk space on my boot2docker vm. I thought it would be incredibly convenient if some of this information was exposed on the cli. It would be nice if I could run a command similar to 

```
boot2docker df
```

and see the disk stats of the vm. Same goes for load and memory usage.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
