### ISSUE TITLE
boot2docker image download progress

### ISSUE THREAD

**Issue by courajs** [boot2docker/boot2docker-cli#365]
Small thing - a download progress indicator (à la wget) for the ISO download would be awesome. It doesn't take long, but commands that run for more than a second without feedback always make me feel just a bit nervous, especially with a new tool.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
