### ISSUE TITLE
boot2docker inside VBox

### ISSUE THREAD

**Issue by claudiaQB** [boot2docker/boot2docker-cli#367]
Dear all,

I would like to use boot2docker for Windows inside a VirtualBox (Windows XP 64-bits, VT-x enabled). I tried to start the last version of boot2docker (v1.6.2) but the boot2docker start command does not end, both using the Boot2docker shortcut or running directly boot2docker start in Windows terminal. The "boot2docker init" actually works, but the "boot2docker up" outputs (I waited for one hour, still up):

Waiting for VM and Docker daemon to start...
...........................................ooooooo

There is no failure, no message, nothing major in Logs from boot2docker-vm and its state is "running". I tried "boot2docker ssh" in another Terminal but it fails with error "error in run: exit status 255" (boot2docker ip fails with "Failed to get VM Host only IP address.  Was the VM initialized using boot2docker?"). I guess this issue can be related to the usage of Windows inside a VB by contrast with "native" Windows. Did someone already successfully use older versions of boot2docker inside a VirtualBox? Or maybe it is not possible...

Thank you very much for your help.

Best regards,
Claudia

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
