### ISSUE TITLE
Running multiple boot2docker with docker-machine 

### ISSUE THREAD

**Issue by thebaron93** [boot2docker/boot2docker-cli#372]
Hello 
I am using docker-machine on Ubuntu 14.04. I have a VM with boot2docker running made by following command `docker-machine create --driver virtualbox dev` . I am trying to create another VM by following `docker-machine create -d virtualbox --virtualbox-boot2docker-url /home/<user name>/Downloads/rancheros.iso rancher` 
It runs , gives the message `Waiting for VM to start` & then `docker@localhost's password` waiting for the password. I tried password `tcuser` ( saw it on #405 ) to no avail.

for VM dev : Boot2Docker version 1.6.2, build master : 4534e65

**Comment by trinitronx** [comment]
This is `boot2docker-cli`, not the `boot2docker` distro project.  Also, `boot2docker-cli` is [being deprecated][1] ([see here][2]) in favor of `docker-machine`.  You do realize you're asking a question about [`docker-machine][3]` in the wrong place?  You're also asking a question about a different docker-based distro.

Anyway... This command worked for me to start a rancher OS box:

```
docker-machine create -d virtualbox --virtualbox-boot2docker-url https://releases.rancher.com/os/latest/machine-rancheros.iso rancher
```

[1]: https://github.com/boot2docker/boot2docker/issues/988
[2]: https://github.com/boot2docker/boot2docker-cli#pending-deprecation
[3]: https://github.com/docker/machine
