### ISSUE TITLE
shellinit command not working reliably on Powershell

### ISSUE THREAD

**Issue by edrevo** [boot2docker/boot2docker-cli#376]
The check performed in https://github.com/boot2docker/boot2docker-cli/pull/356/files to see if the user is in a Windows terminal (cmd or Powershell) is `return os.Getenv("TERM") != ""`.

Unfortunately, this is not a reliable way of checking the type of terminal and it actually clashes with Powershell modules like Posh-Git, which have following code:

``` powershell
function Enable-GitColors {
    $env:TERM = 'cygwin'
}
```

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
