### ISSUE TITLE
multiple boot2docker VM configuration

### ISSUE THREAD

**Issue by riobard** [boot2docker/boot2docker-cli#41]
Or do you just have one? I'm asking this because I'm thinking about the placement of the VMDK disk image. If we assume people will have more than one boot2docker VMs, it is a bit weird to have a single VMDK disk image located in `~/.boot2docker/` instead of having it inside the VirtualBox VM folder. It will probably impact the design of config/profile too.

**Comment by qianyu668899** [comment]
I'd like to follow up this topic, it's true that we can use different profile to create multiple boot2docker instances, and we can use boot2docker ssh to login into them.

But how can we connect to different instances outside the vm. as one VM can only has one ip address?
For example. the default vm is boot2docker-vm, and if we run 'docker COMMAND', it will point to the default vm, how can we make it point to other vm?
