### ISSUE TITLE
Continuous building with Wercker

### ISSUE THREAD

**Issue by schickling** [boot2docker/boot2docker-cli#52]
[Wercker](http://wercker.com/) is currently still in beta but I use it for almost all my projects as CI provider and even for automatic deployment. It's free at the moment and afaik will always be free for open source projects.

It allows to build docker images and run commands on them. We can even export the docker image.

So my propose would be to use Wercker for continuous building of the binary files.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
