### ISSUE TITLE
File sharing via rsync

### ISSUE THREAD

**Issue by riobard** [boot2docker/boot2docker-cli#66]
@SvenDowideit you might want to check this out https://www.vagrantup.com/blog/feature-preview-vagrant-1-5-rsync.html

**Comment by blaggacao** [comment]
Have a look at: https://github.com/brikis98/docker-osx-dev
It seems like a complete take, but unfortunately only on OS X.

**Comment by blaggacao** [comment]
Digging through, I noticed that it doesn't work for windows, So I found https://github.com/thekid/inotify-win/ it's kind of a gluecode, mapping the FileSystemWatch api to an inotify command. I think a competent person, would be able to stick the peaces together.

**Comment by emcrisostomo** [comment]
Hi @blaggacao, as I told you on emcrisostomo/fswatch#88 it wouldn't be difficult writing a `fswatch` monitor for Windows. At the moment, thought, I'm not doing it because I lack time and other issues in the pipeline for `fswatch`.

I had a (very) quick glance to [inotify-win] but it doesn't look like the glue code you are thinking. Instead, it's a (basic) C# port of `inotifywait` tool.

[inotify-win]: https://github.com/thekid/inotify-win/

**Comment by blaggacao** [comment]
@SvenDowideit : maybe a good starting point would be to preinstall rsync in the docker image, so that people who are akin to the topic but do not know the build details of the tc linux can start to find solutions.

**Comment by blaggacao** [comment]
A basic shell script implementation for now is, which is executed in the source directory, if anyone tells me how to dynamically access the boot2docker config values, and "dynamize" source and target values I'll quickly update.
```
#!bin/bash
while inotifywait -r ./*; do
	rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i C:\\Users\\USERNAME\\.ssh\\id_boot2docker" ./* docker@$(boot2docker ip):/target
done
```

I use the inotify port mentioned above. Make sure to have run `tce-load -wi rsync` during your current boot2docker lifetime as its file-system ephemeral.

A re-implementation in go in the boot2docker cli should be however quite easy.

Bi-directional is not needed for the standard "developing on host, running on docker" case. But without this functionality it's really a pain.

**Comment by mattes** [comment]
@blaggacao check out https://github.com/synack/docker-rsync, too.

**Comment by blaggacao** [comment]
The above comment has been updated with a complete bash script.
