### ISSUE TITLE
add a magic 'there's a new version to download' string to b2d-cli version

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#69]
ala docker.

and it would be good to indicate the version of docker they're running. Eventually, it would be good to tie the version numbers together

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
