### ISSUE TITLE
boot2docker (and vbox) don't like it when you move dirs

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#76]
I renamed the .boot2docker dir, so it thinks the vm is both there, and not, and complains horribly.

I'm not sure what we can or should do about corner cases like this, but its worth thinking about

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
