### ISSUE TITLE
boot2docker-cli stop does nothing

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/boot2docker-cli#89]
on windows - I've not tested elsewhere yet.

this is the 0.8.0 release :(

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
